#!/bin/bash

# exit as soon as there is an error
set -o errexit
# abort when an unset variable is used
set -o nounset

# get the root directory (i.e. the directory where this script is located)
ROOT_DIR="$( builtin cd -P "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

BUILD="Release"
BUILD_JOBS=""
VERBOSE=""
OFFLINE_BUILD="no"
INSTALL="no"
PREFIX="$HOME/.local"
CMAKE="cmake"
CMAKE_ONLY="no"
COMPILER="gcc"

USE_MPI="yes"
USE_CUDA="yes"
CUDA_ARCH="auto"
USE_OPENMP="yes"
USE_GMP="no"
USE_CI_FLAGS="no"
USE_SYSTEM_GTEST="no"

# flags affecting only tests
RUN_TESTS="yes"   # whether to run tests if they were compiled (coverage script sets it to no)
TESTS_JOBS="4"

# targets
BUILD_BENCHMARKS="no"
BUILD_EXAMPLES="no"
BUILD_TOOLS="no"
BUILD_TESTS="no"
BUILD_MATRIX_TESTS="no"
BUILD_COVERAGE="no"
BUILD_DOC="no"

# external dependencies
DCMTK_DIR="/usr/include/dcmtk"
# set default value to "none"
CUDA_SAMPLES_DIR="${CUDA_SAMPLES_DIR:-none}"

function print_usage()
{
    cat << EOF
usage: $0 [options] [target ...]

By default, the script does not select any target. Build targets available for
selection are listed below. If the --install option is used, the TNL header
files as well as the selected targets will be installed into the directory
specified by the --prefix option.

Targets:
    all             Special target which includes all other targets.
    benchmarks      Compile the 'src/Benchmarks' directory.
    examples        Compile the 'src/Examples' directory.
    tools           Compile the 'src/Tools' directory.
    tests           Compile unit tests in the 'src/UnitTests' directory (except
                    tests for matrix formats, which have a separate target).
    matrix-tests    Compile unit tests for matrix formats.
    doc             Generate the documentation.

General options:
    --help                                Write this help list and exit.
    --verbose                             Enables verbose build.
    --install=yes/no                      Enables the installation of TNL files. '$INSTALL' by default.
    --prefix=PATH                         Prefix for the installation directory. '$PREFIX' by default.

Options affecting all targets:
    --offline-build=yes/no                Disables online updates during the build. '$OFFLINE_BUILD' by default.
    --build=Debug/Release                 Build type.
    --build-jobs=NUM                      Number of processes to be used for the build. It is set to the number of available CPU cores by default.
    --cmake=CMAKE                         Path to the cmake command. '$CMAKE' by default.
    --cmake-only=yes/no                   Run only the cmake command, don't actually build anything. '$CMAKE_ONLY' by default.
    --compiler=gcc/clang/icc              Selects the compiler to use. '$COMPILER' by default.
    --use-mpi=yes/no                      Enables MPI. '$USE_MPI' by default (OpenMPI required).
    --use-cuda=yes/no                     Enables CUDA. '$USE_CUDA' by default (CUDA Toolkit is required).
    --cuda-arch=all/auto/3.0/3.5/...      Chooses CUDA architecture. '$CUDA_ARCH' by default.
    --use-openmp=yes/no                   Enables OpenMP. '$USE_OPENMP' by default.
    --use-gmp=yes/no                      Enables the wrapper for GNU Multiple Precision Arithmetic Library. '$USE_GMP' by default.

Options for the 'tests' and 'matrix-tests' targets:
    --run-tests=yes/no                    Runs unit tests if they were compiled. '$RUN_TESTS' by default.
    --tests-jobs=NUM                      Number of processes to be used for the unit tests. It is $TESTS_JOBS by default.
    --build-coverage=yes/no               Enables code coverage reports for unit tests (lcov is required). '$BUILD_COVERAGE' by default.
    --use-system-gtest=yes/no             Use GTest installed in the local system and do not download the latest version. '$USE_SYSTEM_GTEST' by default.

External dependencies:
    --dcmtk-dir=PATH                      Path to the DCMTK (Dicom Toolkit) root dir. '$DCMTK_DIR' by default.
    --cuda-samples-dir=PATH               CUDA samples are used by some reference algorithms used in benchmarks. '$CUDA_SAMPLES_DIR' by default.
EOF
}

# handle --help first
for option in "$@"; do
    if [[ "$option" == "--help" ]]; then
        print_usage
        exit 1
    fi
done

# handle options
for option in "$@"; do
    case "$option" in
        --build=*             ) BUILD="${option#*=}" ;;
        --build-jobs=*        ) BUILD_JOBS="${option#*=}" ;;
        --verbose             ) VERBOSE="--verbose" ;;
        --offline-build       ) OFFLINE_BUILD="yes" ;;
        --install=*           ) INSTALL="${option#*=}" ;;
        --install             ) INSTALL="yes" ;;
        --prefix=*            ) PREFIX="${option#*=}" ;;
        --cmake=*             ) CMAKE="${option#*=}" ;;
        --cmake-only=*        ) CMAKE_ONLY="${option#*=}" ;;
        --compiler=*          ) COMPILER="${option#*=}" ;;
        --use-mpi=*           ) USE_MPI="${option#*=}" ;;
        --use-cuda=*          ) USE_CUDA="${option#*=}" ;;
        --cuda-arch=*         ) CUDA_ARCH="${option#*=}";;
        --use-openmp=*        ) USE_OPENMP="${option#*=}" ;;
        --use-gmp=*           ) USE_GMP="${option#*=}" ;;
        --run-tests=*         ) RUN_TESTS="${option#*=}" ;;
        --tests-jobs=*        ) TESTS_JOBS="${option#*=}" ;;
        --build-coverage=*    ) BUILD_COVERAGE="${option#*=}" ;;
        --use-ci-flags=*      ) USE_CI_FLAGS="${option#*=}" ;;
        --use-system-gtest=*  ) USE_SYSTEM_GTEST="${option#*=}" ;;
        --dcmtk-dir=*         ) DCMTK_DIR="${option#*=}" ;;
        --cuda-samples-dir=*  ) CUDA_SAMPLES_DIR="${option#*=}" ;;
        -*                    )
            echo "Unknown option $option. Use --help for more information." >&2
            exit 1
            ;;
        *) break ;;
    esac
    shift
done

# check the build type
if [[ ! "Release Debug RelWithDebInfo" =~ "$BUILD" ]]; then
    echo "Unknown build type: $BUILD. The available build types are: Release, Debug, RelWithDebInfo." >&2
    exit 1
fi

# handle targets
for target in "$@"; do
    case "$target" in
        all)
            BUILD_BENCHMARKS="yes"
            BUILD_EXAMPLES="yes"
            BUILD_TOOLS="yes"
            BUILD_TESTS="yes"
            BUILD_MATRIX_TESTS="yes"
            BUILD_DOC="yes"
            ;;
        benchmarks)     BUILD_BENCHMARKS="yes" ;;
        examples)       BUILD_EXAMPLES="yes" ;;
        tools)          BUILD_TOOLS="yes" ;;
        tests)          BUILD_TESTS="yes" ;;
        matrix-tests)   BUILD_MATRIX_TESTS="yes" ;;
        doc)            BUILD_DOC="yes" ;;
        *)
            echo "Unknown target $target. The available targets are: all, benchmarks, examples, tools, tests, matrix-tests, doc." >&2
            echo "Use --help for more information." >&2
            exit 1
    esac
    shift
done

if [[ "$COMPILER" == "gcc" ]]; then
   export CXX=g++
   export CC=gcc
   export CUDA_HOST_COMPILER=g++
elif [[ "$COMPILER" == "clang" ]]; then
   export CXX=clang++
   export CC=clang
   export CUDA_HOST_COMPILER=clang++
elif [[ "$COMPILER" == "icc" ]]; then
   export CXX=icpc
   export CC=icc
   export CUDA_HOST_COMPILER=icpc
else
   echo "Error: the compiler '$COMPILER' is not supported. The only options are 'gcc', 'clang' and 'icc'." >&2
   exit 1
fi

if [[ ! $(command -v cmake) ]]; then
   echo "Error: cmake is not installed. See http://www.cmake.org/download/" >&2
   exit 1
fi

if [[ $(command -v ninja) ]]; then
   generator=Ninja
   check_file="build.ninja"
else
   generator="Unix Makefiles"
   check_file="Makefile"
fi

BUILD_DIR="builddir/$BUILD"
cmake_command=(
   "$CMAKE" -B "$BUILD_DIR" -S "$ROOT_DIR" -G "$generator"
         -DCMAKE_BUILD_TYPE="$BUILD"
         -DCMAKE_INSTALL_PREFIX="$PREFIX"
         -DDCMTK_DIR="$DCMTK_DIR"
         -DTNL_OFFLINE_BUILD="$OFFLINE_BUILD"
         -DTNL_USE_CUDA="$USE_CUDA"
         -DTNL_CUDA_ARCH="$CUDA_ARCH"
         -DTNL_USE_OPENMP="$USE_OPENMP"
         -DTNL_USE_MPI="$USE_MPI"
         -DTNL_USE_GMP="$USE_GMP"
         -DTNL_USE_CI_FLAGS="$USE_CI_FLAGS"
         -DTNL_USE_SYSTEM_GTEST="$USE_SYSTEM_GTEST"
         -DTNL_BUILD_BENCHMARKS="$BUILD_BENCHMARKS"
         -DTNL_BUILD_EXAMPLES="$BUILD_EXAMPLES"
         -DTNL_BUILD_TOOLS="$BUILD_TOOLS"
         -DTNL_BUILD_TESTS="$BUILD_TESTS"
         -DTNL_BUILD_MATRIX_TESTS="$BUILD_MATRIX_TESTS"
         -DTNL_BUILD_COVERAGE="$BUILD_COVERAGE"
         -DTNL_BUILD_DOC="$BUILD_DOC"
)

# handle CUDA_SAMPLES_DIR - only used for one benchmark, the CMakeLists.txt
# expects it in the environment
export CUDA_SAMPLES_DIR

# Skip running cmake if it was already run and the cmake command is the same.
# The build system (e.g. make) will call it automatically if necessary (e.g.
# when some CMakeLists.txt changes).
if [[ -f ".cmake_command" ]]; then
   last_cmake_command=$(cat "$BUILD_DIR/.cmake_command" 2>/dev/null)
else
   last_cmake_command=""
fi
if [[ ! -f "$check_file" ]] || [[ "$last_cmake_command" != "${cmake_command[@]}" ]]; then
   echo "Configuring ${BUILD} TNL ..."
   "${cmake_command[@]}"
   echo -n "${cmake_command[@]}" > "$BUILD_DIR/.cmake_command"
fi

if [[ ${CMAKE_ONLY} == "yes" ]]; then
   exit 0
fi

# install dependencies into $PREFIX if they are not found system-wide
pkg-config --exists tinyxml2 || "$ROOT_DIR/scripts/install_tinyxml2" --prefix "$PREFIX"

if [[ -n ${BUILD_JOBS} ]]; then
   echo "Building ${BUILD} TNL using $BUILD_JOBS parallel jobs ..."
else
   # number of processors is unknown
   echo "Building ${BUILD} TNL ..."
   # get the number of physical cores present on the system, even with multiple NUMA nodes
   # see https://unix.stackexchange.com/a/279354
   BUILD_JOBS=$(lscpu --all --parse=CORE,SOCKET | grep -Ev "^#" | sort -u | wc -l)
fi

# build the targets
if ! "$CMAKE" --build "$BUILD_DIR" $VERBOSE --parallel "$BUILD_JOBS" --target all; then
   exit 1
fi

if [[ "$INSTALL" == "yes" ]]; then
   # install the targets
   if ! "$CMAKE" --install "$BUILD_DIR" $VERBOSE; then
      exit 1
   fi
fi

if [[ "$BUILD_DOC" == "yes" ]]; then
   "$ROOT_DIR/Documentation/build" --prefix="$PREFIX" --install="$INSTALL" --output-snippets-path="$(pwd)/$BUILD_DIR/output_snippets/"
fi

if [[ "$BUILD_TESTS" == "yes" ]] || [[ "$BUILD_MATRIX_TESTS" == "yes" ]]; then
   if [[ "$RUN_TESTS" == "yes" ]]; then
      OMP_NUM_THREADS="$TESTS_JOBS" CTEST_PARALLEL_LEVEL="$TESTS_JOBS" CTEST_OUTPUT_ON_FAILURE=1 "$CMAKE" --build "$BUILD_DIR" $VERBOSE --parallel "$BUILD_JOBS" --target test
   fi
fi
