#!/usr/bin/env bash

tnl-grid-setup --dimensions 2 \
               --origin-x 0.0 \
               --origin-y 0.0 \
               --proportions-x 1.0 \
               --proportions-y 1.0 \
               --size-x 100 \
               --size-y 100

tnl-navier-stokes-Ausm-Plus
              --initial-condition riemann-problem \
              --time-discretisation explicit \
              --boundary-conditions-type cavity \
              --boundary-conditions-constant 0 \
              --operator-right-hand-side Navier-Stokes \
              --discrete-solver euler \
              --time-step 2e-6 \
              --snapshot-period 2e-4 \
              --convergence-residue 0.0 \
              --final-time 2e-2 \
              --initial none \
              --speed-increment 0.05 \
              --inviscid-operators-dynamical-viscosity 1.0 \
              --SED-pressure 10000 \
              --SWD-pressure 10000 \
              --NED-pressure 10000 \
              --NWD-pressure 10000 \
              --SED-velocity-0 0 \
              --SWD-velocity-0 0 \
              --NED-velocity-0 0 \
              --NWD-velocity-0 0 \
              --SED-velocity-1 0 \
              --SWD-velocity-1 0 \
              --NED-velocity-1 0 \
              --NWD-velocity-1 0 \
              --cavity-speed 2.0

tnl-view --mesh mesh.tnl --input-files *tnl     
